# Generated by Django 4.0.4 on 2022-05-09 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro',
            name='slug',
            field=models.SlugField(editable=False, unique=True),
        ),
    ]
