# Generated by Django 4.0.4 on 2022-05-13 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0002_alter_cadastro_data_de_nascimento_do_aluno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastro',
            name='comentarios',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
    ]
