# Generated by Django 4.0.4 on 2022-05-13 02:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0003_cadastro_comentarios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro',
            name='comentarios',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
        ),
    ]
